### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by klugier** [anboto/Controls4U#1]
This repository needs to have better README.md. Right now when opening from UppHub, you do not know what it is offer. At least there should be list of controls.

![Screenshot_20221117_194202](https://user-images.githubusercontent.com/6963025/202531243-1a960317-3f02-4ffb-8e55-eb6b3bb59929.png)

**Comment by izabala123** [comment]
Hi Zbigniew

I agree. I will amend the text right away.

Iñaki

**Comment by izabala123** [comment]
Hi Zbigniew

I have updated the files, I hope they are ok now. Thanks for your help.

Iñaki

**Comment by izabala123** [comment]
Hi Zbigniew

Please confirm that this is solved. Thank you.

Iñaki

**Comment by klugier** [comment]
It looks good. Thank you!
